### ISSUE TITLE
Download links throw 404

### ISSUE THREAD

**Issue by bonfish** [goldsky/FileDownload-R#27]
Hi!

Snippet call
[[!FileDownload? &getDir=`[[++base_path]]some/path/]]`
is in the start document. It loads and shows all files correctly. But when I try to download something when accessing it from the base_url (http://my.site), I see the issue form the subject.

When I load http://my.site/index.php?id=1 - everything works fine. 
All the pathes are equal on both pages.
MODX Revo 2.2.11. Tested on localhost (Ubuntu server 12.04.3) and on Hetzner VPS. 

The faulty link: http://bonflash.it.cx/modx-revo-test/
The working  link: http://bonflash.it.cx/modx-revo-test/index.php?id=1

Thanks!

**Comment by goldsky** [comment]
I'm closing this issue.
If problem persists, please post back.
