### ISSUE TITLE
URLs with non-ASCII symbols give 403 (or 401) errors

### ISSUE THREAD

**Issue by bonfish** [goldsky/FileDownload-R#28]
When SEF is on, a page with FileDownload call has some non-ASCII (for example, Russian) symbols in it's alias and hashing in FileDownload is enabled, clicking download links on this page thows 403 (or 401 on my other Revo instance). If the alias is in ASCII only, everything works fine.

The pages are absolutely identical, except for their IDs, titles and aliases. The call is:
```
[[!FileDownload? &getDir=`[[++base_path]]price-lists/` &directLink=`0`]]
```
Here it works: http://baikal-saz.ru/personal.html
Here it doesn't: http://baikal-saz.ru/%D0%BB%D0%B8%D1%87%D0%BD%D1%8B%D0%B9-%D0%BA%D0%B0%D0%B1%D0%B8%D0%BD%D0%B5%D1%82.html
_____________
I would also like to mention, that the same Russian symbols don't show up correctly in the list (though, they download OK). For example, on the page above the balnk-named text file is actually called "приколы.txt"

**Comment by goldsky** [comment]
does this work for you?
https://github.com/goldsky/FileDownload-R/issues/33#issuecomment-70101291

**Comment by goldsky** [comment]
https://github.com/goldsky/FileDownload-R/issues/33#issuecomment-186193628
