### ISSUE TITLE
Russian text problem

### ISSUE THREAD

**Issue by TITAN-UZ** [goldsky/FileDownload-R#33]
Hi!

How to fix russian text!

Set locale UTF8 does not help

**Comment by zverbeta** [comment]
One option replace in file filedownload.class.php line 973 
before:
``` utf8_encode($baseName) ```
after: 
``` (preg_match('!!u', $baseName)) ? $baseName : utf8_encode($baseName) ```

**Comment by goldsky** [comment]
What is `!!u` ?

**Comment by zverbeta** [comment]
This is trick check utf-8 

from doc. 

"This modifier turns on additional functionality of PCRE that is incompatible with Perl. Pattern and subject strings are treated as UTF-8."

**Comment by elfgokou** [comment]
I have this problem with chinese text,BTW where is filedownload.class.php,

**Comment by goldsky** [comment]
![filedownload internationalizaetion](https://cloud.githubusercontent.com/assets/308524/13175477/3f8e4bfe-d73d-11e5-9130-1957946f1427.png)
