### ISSUE TITLE
Disable CSS Link Adding

### ISSUE THREAD

**Issue by Froggiewalker** [goldsky/FileDownload-R#41]
Hi,
I'am using CSS preprocessor Sass and importing fd.css to my app.css. To avoid double loading styles, I would like to disable appending of LINK tag with fd.css stylesheet into HEAD.
Based on documentation, I set &fileCss parameter to `` (empty string), but the empty LINK tag is still appending.
It would be nice, if FD-R tested &fileCss first and if it’s empty, no LINK was appended.
Thanks for Your great work on FD-R.
Froggiewalker

**Comment by goldsky** [comment]
try ``` &fileCss=`disabled` ```

**Comment by Froggiewalker** [comment]
Great, this is what I needed to know. Thanks

**Comment by goldsky** [comment]
I think I missed that on rtfm, thanks for notifying.
