### ISSUE TITLE
saltText not working

### ISSUE THREAD

**Issue by mtalvenheimo** [goldsky/FileDownload-R#44]
Hi,
Seems that adding saltText parameter makes no difference?

**Comment by goldsky** [comment]
difference to what?
are you using ```&directLink=`1` ```?

**Comment by mtalvenheimo** [comment]
I'm not using directlink.

Documentation:
http://rtfm.modx.com/extras/revo/filedownload-r/filedownload-r.filedownload
>saltText | This text will be added to the file's hashed link to disguise the direct path

If i understand this right, saltText should be added to hashed link? Although saltText parameter makes no difference to link?

**Comment by goldsky** [comment]
I'm going to check this as well.
http://forums.modx.com/thread/97868/filedownload-r-salttext-param-not-working#dis-post-529199
