### ISSUE TITLE
Display subset of files (based on filename)

### ISSUE THREAD

**Issue by pierzy** [goldsky/FileDownload-R#46]
Hi goldsky! 
I would like to display only files with a name containing a given substring (in fact the substring will be the username of the currently logged in user). I thought to do it in _getDirContents around line 840
by only appending $fileInfo if it satisfies some criteria. Do you see a better way of doing this?
Maybe this could also be a feature request.
Best regards,
Pier

**Comment by goldsky** [comment]
by using user's id as folder.
so you can pull out files using 
```
&getDir=`path/to/[[+modx.user.id]]/`
```
