### ISSUE TITLE
Can't download from nested directories

### ISSUE THREAD

**Issue by BobRay** [goldsky/FileDownload-R#48]
Hi Goldsky,

This is a great extra, but I'm having a little trouble. I've left everything at its default and used this tag:

    [[!FileDownload? 
        &getDir=`[[++core_path]]components/notify` 
        &browseDirectories=`1` 
        &groupByDirectory=`1` 
    ]] 

Everything looks fine and I can navigate through the subdirectories, but I can only download files that are in the notify directory. Trying to download files in directories below it just reloads the page, which shows no output from FDR.

Downloading files in the notify directory works fine.

Am I doing something wrong?

**Comment by goldsky** [comment]
I think there's a new bug. I will investigate this. Thanks for reporting.

**Comment by goldsky** [comment]
try 2.0.0-pl
